"""init investigations

Revision ID: 512383a6f34a
Revises: 
Create Date: 2026-05-06 13:41:21.711622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512383a6f34a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'FAILED', name='investigationstatus'), nullable=True),
    sa.Column('drift_event', sa.JSON(), nullable=True),
    sa.Column('triage_result', sa.String(), nullable=True),
    sa.Column('proposed_action', sa.String(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('checkpoint_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigations')
    # ### end Alembic commands ###
